language: java
sudo: false
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "alu0100710298-github"
    token:
      secure: "f4a21e6428f07a58ceb1740e3cd01091ae148e5e"

jdk:
  - oraclejdk8
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package javadoc:javadoc
  - sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: 
  recipients:
    - alu0100710298@ull.edu.es
on_success: always
on_failure: always
